project_id = "nawhpweyisawxaymmusg"

[functions.import-insumos]
verify_jwt = false

[functions.import-inventory]
verify_jwt = false

[functions.extract-dose-from-image]
verify_jwt = false

[functions.criar-contrato-zapsign]
verify_jwt = false
